### ISSUE TITLE
Conversation list should be sorted by last received

### ISSUE THREAD

**Issue by neilio** [shusain93/Andromeda-iMessage#1]
When a new message comes in, the conversation and contact it's connected to doesn't rise to the top of the conversation list, so you have to go digging to find it.

**Comment by ezhes** [comment]
This is a mild bug with the fact that I haven't setup sockets yet. If you rotate your device and back it ends up reloading and is there at the top. Without sockets this really doesn't work well for continuous fast conversation, mostly for just one offs. If you need to trigger a refresh in the message view you can either tap the notification or again use the rotate thing. I'll setup sockets soon , it's annoying to me too.
