### ISSUE TITLE
App keeps crashing whenever I try to connect to my server!

### ISSUE THREAD

**Issue by SethuSenthil** [shusain93/Andromeda-iMessage#10]
Whenever I try to connect to the server using the app, while trying to connect to the server, the app immediately crashed on my phone (Android 7.1.2), this happens when I also type in the wrong credentials. Everything is running fine on my mac, its that the other app.

**Comment by shusain93** [comment]
That sucks -- to bad you didn't tell me anything about your issue.

**Comment by ezhes** [comment]
Crash logs seem to suggest your server isn’t responding correctly and is replying with an empty version number. What do you get when you go to http://yourip/isUp?t=yourtoken
