### ISSUE TITLE
No notifications for new incoming messages.

### ISSUE THREAD

**Issue by tristanphan** [shusain93/Andromeda-iMessage#12]
No notifications show when someone sends me a new message, or even any indication of a new message when I open the app. I think the notifications are a bug, but at least make it do something when you open the app, like bolded chat names for new messages.

**Comment by ezhes** [comment]
You’ve configured something wrong yourself to not get notifications. The bit about not flagging conversations is a known limitation.

Are you sure your api key is correct for IFTTT?

**Comment by tristanphan** [comment]
I copy and pasted the IFTTT key from the Documentation page under Webhooks into the second field in the app. Yes, I launched it with the script.

**Comment by tristanphan** [comment]
Actually I typed it because I couldn't copy and paste.

**Comment by ezhes** [comment]
You can right click to paste. The shortcut AFAIK doesnt work.

**Comment by tristanphan** [comment]
The notifications for the text I sent myself through another iPad 7 hours ago finally came... 7 hours after the message was received on the Mac.

**Comment by ezhes** [comment]
Notifications aren’t my issue. The app polls the DB every five seconds and sends the notifications. The issue is in IFTTT or Pushbullet if you don’t have a log to show me.

**Comment by tristanphan** [comment]
Also clicking on notifications from a group chat sends me to the private chat of the person who sent the message in the group chat instead of the actual group chat.
