### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by jnorman-nyc** [shusain93/Andromeda-iMessage#13]
What’s your take on the security of passing the message off from iMessage (end to end encryption) to Andromeda (no encryption?)? Thanks and great project.

**Comment by ezhes** [comment]
This project is 100% security through obscurity. I hope soon to upgrade to SSL sockets and server but it’s a time a issue and will require a rewrite. The project is small enough that unless someone specifically wants to attack YOU it’s safe. 

Also is this a question or a complaint? Haha.

**Comment by jnorman-nyc** [comment]
Oh it was a total question. I’m not familiar with how the iMessage would be handed off. Thanks!

**Comment by ezhes** [comment]
Yeah, it's on the roadmap. I fully aware that unencrypted iMessage isn't great but this was really a hack.

**Comment by jnorman-nyc** [comment]
Huh. I wonder if you could use another messaging app with encryption (like Signal) to hand off the iMessage to it? (I am obviously not a programmer so thank you for humoring me).

**Comment by vrchlabak** [comment]
Hi:

Have you tested the server with MacOS High Sierra? Does it still function like Sierra?

Please let me know.

Thanks!


On Oct 5, 2017, at 7:34 AM, Salman Husain <notifications@github.com> wrote:

Yeah, it's on the roadmap. I fully aware that unencrypted iMessage isn't great but this was really a hack.

**Comment by ezhes** [comment]
Please create a new issue next time. Do not pick a random issue. No, I have not checked. If it's broken let me know.
