### ISSUE TITLE
Can send but not receive

### ISSUE THREAD

**Issue by scottstables** [shusain93/Andromeda-iMessage#17]
Hi - not sure what is happening - 

message in the terminal window that I think might yield something is 

"2017-11-23 17:23:23.111 MessageProxy[3658:435578] [Accounts] Failed to update account with identifier A4F9FDB3-7256-4A1A-AE87-B11A6952BF6A, error: Error Domain=ABAddressBookErrorDomain Code=1002 "(null)"

Any ideas ?

BTW- this looks great.

**Comment by ezhes** [comment]
I swear to god I will forever pay for not filtering that message out. That error doesn't mean anything, it's just the OS being too verbose. What do you mean you don't receive messages?

**Comment by scottstables** [comment]
Sorry. I can send a message from the Android which is received by an iMessage user (I also see it on my mac). I see the response coming back to me (it shows in Message on the mac) but never makes it over to the Android. BTW - I assume I don't need to use IFFFT for this part of the functionality ?

**Comment by ezhes** [comment]
No, did you port forward the socket as well as the main API? They're two separate ports

**Comment by scottstables** [comment]
Thats it ! I think I had an error with the port forwarding... many thanks
