### ISSUE TITLE
Get this toast when starting AndromedaB: "Unable to load conversationJSONDatabase! com.android.volley.TimeoutError"

### ISSUE THREAD

**Issue by mentalbob** [shusain93/Andromeda-iMessage#18]
Conversation loading timeouts are happening all the time for me now.  I was going to reopen the original issue since this was the real problem but I couldn't find it in closed issues.  Below is a capture of the console during an Android Studio but it doesn't look like it says anything interesting.

`11/29 11:51:42: Launching app
$ adb shell am start -n "eu.aero2x.andromedab/eu.aero2x.andromedab.ContactSelect" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: eu.aero2x.andromedab.test | eu.aero2x.andromedab
Waiting for application to come online: eu.aero2x.andromedab.test | eu.aero2x.andromedab
Waiting for application to come online: eu.aero2x.andromedab.test | eu.aero2x.andromedab
Connecting to eu.aero2x.andromedab
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/System.out: Sending WAIT chunk
I/art: Debugger is active
Connected to the target VM, address: 'localhost:8621', transport: 'socket'
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1455)
W/System: ClassLoader referenced unknown path: /data/app/eu.aero2x.andromedab-2/lib/x86
D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
D/FirebaseInstanceId: Missing wake lock permission, service start may be delayed
I/DynamiteModule: Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:0
I/DynamiteModule: Selected local version of com.google.android.gms.flags
W/System: ClassLoader referenced unknown path: 
W/System: ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86
D/ApplicationLoaders: ignored Vulkan layer search path /system/priv-app/PrebuiltGmsCore/lib/x86:/system/fake-libs:/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86:/system/lib:/vendor/lib for namespace 0xb05d7090
W/DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
W/System: ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86
D/ApplicationLoaders: ignored Vulkan layer search path /system/priv-app/PrebuiltGmsCore/lib/x86:/system/fake-libs:/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86:/system/lib:/vendor/lib for namespace 0xb05d70d0
I/DynamiteModule: Considering local module com.google.android.gms.crash:0 and remote module com.google.android.gms.crash:10
I/DynamiteModule: Selected remote version of com.google.android.gms.crash, version >= 10
W/System: ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000003/n/x86
I/FirebaseCrashApiImpl: FirebaseCrashApiImpl created by ClassLoader bxi[DexPathList[[zip file "/system/priv-app/PrebuiltGmsCore/app_chimera/m/DynamiteModulesC.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000003/n/x86, /system/lib, /vendor/lib]]]
I/DynamiteModule: Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:0
I/DynamiteModule: Selected local version of com.google.android.gms.flags
W/DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
I/FirebaseCrashApiImpl: FirebaseCrash reporting API initialized
I/FA: App measurement is starting up, version: 10298
I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
V/FA: Collection enabled
V/FA: App package, google app id: eu.aero2x.andromedab, 1:66212562902:android:88a47daa25f3d5bb
I/FA: To enable faster debug mode event logging run:
        adb shell setprop debug.firebase.analytics.app eu.aero2x.andromedab
D/FA: Debug-level message logging enabled
V/FA: Registered activity lifecycle callback
I/FirebaseCrash: FirebaseCrash reporting initialized com.google.android.gms.internal.zzbnq@4187833
I/FirebaseInitProvider: FirebaseApp initialization successful
I/InstantRun: starting instant run server: is main process
V/FA: Using measurement service
V/FA: Connecting to remote service
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
I/art: Starting a blocking GC Instrumentation
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Not able to initialize class for SetValues: java.lang.Class<eu.aero2x.andromedab.ContactSelect>
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
V/FA: onActivityCreated
I/System.out: Firebase notification token:null
D/onNewIntent: Launched without a URI param
V/FA: Using measurement service
V/FA: Connection attempt already in progress
V/FA: Activity resumed, time: 2973592
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0xa56abd80: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0xa56abd80: ver 2 0 (tinfo 0xa0da2d50)
W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
D/EGL_emulation: eglMakeCurrent: 0xa56abd80: ver 2 0 (tinfo 0xa0da2d50)
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 2
D/FirebaseInstanceId: background sync failed: AUTHENTICATION_FAILED, retry in 10s
E/FA: Name must consist of letters, digits or _ (underscores). Type, name: event, server_version_1.2.2
I/FA: Tag Manager is not found and thus will not be used
D/FA: Logging event (FE): _err, Bundle[{_o=auto, _el=20, _ev=server_version_1.2.2, _sc=ContactSelect, _si=-3144674906599061657, _err=2}]
V/FA: Session started, time: 3000047
I/art: Do partial code cache collection, code=30KB, data=20KB
D/FirebaseInstanceId: Missing wake lock permission, service start may be delayed
D/FA: Logging event (FE): _s, Bundle[{_o=auto, _sc=ContactSelect, _si=-3144674906599061657}]
I/art: After code cache collection, code=28KB, data=19KB
I/art: Increasing code cache capacity to 128KB
I/FirebaseCrash: Sending crashes
V/FA: Inactivity, disconnecting from the service
D/FirebaseInstanceId: background sync failed: AUTHENTICATION_FAILED, retry in 20s
D/Socket: Starting
D/SocketPrep: ACK
D/SocketPrep: READY
D/SocketPrep: Socket server has accepted our login! Ready
D/FirebaseInstanceId: Missing wake lock permission, service start may be delayed
D/FirebaseInstanceId: background sync failed: AUTHENTICATION_FAILED, retry in 40s
E/FirebaseCrash: Error sending crash report: IOException while sending a crash report
E/FirebaseCrash: Error sending crash report: IOException while sending a crash report
D/SocketPrep: Failed, shutting down! ---> Will retry in 5 seconds
W/System.err: java.net.SocketTimeoutException: Read timed out
W/System.err:     at java.net.SocketInputStream.socketRead0(Native Method)
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:151)
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:120)
W/System.err:     at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
W/System.err:     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
W/System.err:     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
W/System.err:     at java.io.InputStreamReader.read(InputStreamReader.java:184)
W/System.err:     at java.io.BufferedReader.fill(BufferedReader.java:172)
W/System.err:     at java.io.BufferedReader.readLine(BufferedReader.java:335)
W/System.err:     at java.io.BufferedReader.readLine(BufferedReader.java:400)
W/System.err:     at eu.aero2x.andromedab.SocketClient$1.doInBackground(SocketClient.java:48)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
D/Socket: Starting
D/SocketPrep: ACK
D/SocketPrep: READY
D/SocketPrep: Socket server has accepted our login! Ready`

**Comment by ezhes** [comment]
What happens when you access IP:8735/conversations?t=<token>? If that’s fine when you access on the server machine you have a networking issue

**Comment by mentalbob** [comment]
It loads fine.

**Comment by ezhes** [comment]
Yeah that’s an issue with your network setup then. This error appears obviously when the phone can’t reach the server in time. The test I had you do shows that the server can generate the conversation list fast enough so it’s not getting stuck and timing out or whatever. Is the app always like this or does it work sometimes? Might be a firewall issue which is just dropping packets instead of rejecting them.

**Comment by mentalbob** [comment]
Isn't another possibility that volley is timing out before iMessage_Proxy finishes generating the rather large JSON response?   I should've added that the manual pull of the conversations takes several seconds to load.  AndromedaB looks like it timeouts and displays the toast after about 5 seconds which is a really short timeout.   How do you change volley's default timeout?

**Comment by ezhes** [comment]
Volley has a default timeout of 5000ms as it turns out which you guessed pretty well, ha!

How many conversations are you returning? Easy to find out if you go to jsonviewer.stack.hu and paste in your JSON output. It's not difficult to raise the timeout (https://stackoverflow.com/a/33566615/1166266 , add into here https://github.com/shusain93/Andromeda-iMessage/blob/master/app/src/main/java/eu/aero2x/andromedab/RemoteMessagesInterface.java)  but I'm not sure why it's taking so long to generate your conversation table. I have 118 conversations and it takes 973 ms to generate the payload. 

You can see your timings with the chrome dev tools, click over to the network panel, refresh, click on the main request, and then look at timings, TTFB.

How old is your server's hardware? I'm running a 2010 Macbook Air with a BLISTERING FAST Core 2 Duo (lol) and have no trouble with timeouts.

**Comment by mentalbob** [comment]
Heh.  It's a 2012 mac mini but the WiFi net its on isn't the fastest.  Also, I have many conversations and it looks like some of them are as old as 2013 so it could be quite a large list.  Update:  looks like 367 conversations.  Also note that it does load sometimes so it could depend on network+cpu+i/o shenanagins.  I'll give your suggestion a whirl and let you know what happens.  Thanks!

**Comment by ezhes** [comment]
Yeah, not sure 367 conversations is going to play nice on this because it'll parse every single one of them every time you visit the conversations page. You could raise the timeout (bandaid) or archive some of your conversations from back in 2013. I could of course do a fancy paginated conversation view so it'll only parse the most recent 25 or whatever but that sounds like a lot of work imo and I'm currently swamped with other projects. You really should only have to bandaid fix the getConversations method but that'll mean the app will take a really long time to launch since it reloads from the server every time you relaunch the app. If you don't have a ton of conversations (ie less than 180) you can beat a real iPhone cold launching Messages on iOS 11 (whether this speaks to my incredible engineering or Apple's bad optimization that's anyone's guess :P )

**Comment by mentalbob** [comment]
Yep.   Added the SetRetryPolicy to your code like below and it worked like a champ!

```
public static void getConversations (Context context, Response.Listener<String> onResponse,Response.ErrorListener onError) {
        // Instantiate the RequestQueue.
        RequestQueue queue = Volley.newRequestQueue(context);
        StringRequest stringRequester = new StringRequest(Request.Method.GET,API_URL + "/conversations?t=" + API_PROTECTION_TOKEN,onResponse,onError);

        // change timeout to a more reasonable 10 seconds
        stringRequester.setRetryPolicy(new DefaultRetryPolicy(
                10000,
                DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
                DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));

        // Add the request to the RequestQueue.
        queue.add(stringRequester);
    }
```

**Comment by ezhes** [comment]
Well ill be darned! If you want credit for this I’ll  merge a pull request from you. Add a comment linking this issue too if you would.

**Comment by mentalbob** [comment]
Actually I would.  This is my first foray into Android development (ex-Windows developer here) so I'd like something to show off :).  I'll push it to my fork and send you the pull request when I get the chance later this week.

**Comment by mentalbob** [comment]
I sent a pull request with the fix.   Enjoy!  On a slightly tangential topic, I refactored your settings dialog so that it can be invoked from the action menu and I added a refresh action.  Would you be interested in these changes?

**Comment by ezhes** [comment]
Merged!

Sure! I'll take a look.
