### ISSUE TITLE
Doesn't seem to get notifications

### ISSUE THREAD

**Issue by mentalbob** [shusain93/Andromeda-iMessage#4]
Hi,  I noticed your blurb for this one of the piemessage issue threads so I decided to try it out.  Works great except Andromeda itself doesn't seem to be updating when I get a message notification.  I know I'm getting notifications because both IFTTT and Pushbullett annoy me with notifications (I'll have to figure out how to quiet them when i get this fully working).   I have to kill the Andromeda app restart it to get the latest messages.

**Comment by ezhes** [comment]
If you click the notification it should open the app and reload the conversation automatically. Currently I have no way for it to automatically ready from the background. Also, if you ever need to refresh anything just rotate your device. 

For Ifftt spam you probably either have two recipies or you checked the 'notify me when this runs' box

**Comment by mentalbob** [comment]
Got it, thanks!

**Comment by ezhes** [comment]
Can you post what you were doing wrong/or what fixed the problem? Just so people of the future can search
