### ISSUE TITLE
Andromeda crashes if ports aren't entered in initial configuration screen

### ISSUE THREAD

**Issue by mentalbob** [shusain93/Andromeda-iMessage#5]
Dunno if you know about this already, but the initial configuration screen implies that If i leave the port fields blank the defaults will be taken.   If I leave them blank, the app crashes right after I hit submit button.  Filling in the fields with values works.

**Comment by ezhes** [comment]
Huh yeah didn't think of that. Developer UI design strikes again

**Comment by ezhes** [comment]
Fixed this in the latest commit. It'll use a default value now. Next update will include this. Thanks for reporting!
