### ISSUE TITLE
REQUEST / Inquiry Samsung Gear S3

### ISSUE THREAD

**Issue by vrchlabak** [shusain93/Andromeda-iMessage#7]
do you have any plans on building client / app for Samsung Gear S3? Or is there anyway to receive Pushbullet notifications on the device (Gear S3) that you might be able to think of?? This is natively without the need of being connected to the synced android via BT. This is because the phone's PB notifications aren't shared on the watch.

the later wouldn't allow you to respond to an iMessage, but at least you would be aware of it and could respond via text / call.

thanks in advance!!

**Comment by ezhes** [comment]
Yeah sorry I don't know -- if you bought me one and mailed it to me I'd check it out though :P 

You'd have to go from scratch although the API is really simple. Check out the main class in the server project if you want.
